
package com.maitao.weservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ContractWebService", targetNamespace = "http://server.ws.api.contract.goldpalm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContractWebService {


    /**
     * 
     * @param complementSignRequest
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitSign", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.SubmitSign")
    @ResponseWrapper(localName = "submitSignResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.SubmitSignResponse")
    public String submitSign(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "complementSignRequest", targetNamespace = "")
        ComplementSignRequest complementSignRequest);

    /**
     * 
     * @param contractno
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContractBaseInfo", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.GetContractBaseInfo")
    @ResponseWrapper(localName = "getContractBaseInfoResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.GetContractBaseInfoResponse")
    public String getContractBaseInfo(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "contractno", targetNamespace = "")
        String contractno);

    /**
     * 
     * @param password
     * @param code
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authentication", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.Authentication")
    @ResponseWrapper(localName = "authenticationResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.AuthenticationResponse")
    public String authentication(
        @WebParam(name = "code", targetNamespace = "")
        String code,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param submitContractRequest
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadContract", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.UploadContract")
    @ResponseWrapper(localName = "uploadContractResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.UploadContractResponse")
    public String uploadContract(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "submitContractRequest", targetNamespace = "")
        SubmitContractRequest submitContractRequest);

    /**
     * 
     * @param submitStatusRequest
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitStatus", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.SubmitStatus")
    @ResponseWrapper(localName = "submitStatusResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.SubmitStatusResponse")
    public String submitStatus(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "submitStatusRequest", targetNamespace = "")
        SubmitStatusRequest submitStatusRequest);

    /**
     * 
     * @param confirmRequest
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "confirmContractWithEseal", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.ConfirmContractWithEseal")
    @ResponseWrapper(localName = "confirmContractWithEsealResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.ConfirmContractWithEsealResponse")
    public String confirmContractWithEseal(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "confirmRequest", targetNamespace = "")
        ConfirmRequest confirmRequest);

    /**
     * 
     * @param authcode
     * @param code
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticationOTA", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.AuthenticationOTA")
    @ResponseWrapper(localName = "authenticationOTAResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.AuthenticationOTAResponse")
    public String authenticationOTA(
        @WebParam(name = "code", targetNamespace = "")
        String code,
        @WebParam(name = "authcode", targetNamespace = "")
        String authcode);

    /**
     * 
     * @param cancelContractRequest
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelContract", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.CancelContract")
    @ResponseWrapper(localName = "cancelContractResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.CancelContractResponse")
    public String cancelContract(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "cancelContractRequest", targetNamespace = "")
        CancelContractRequest cancelContractRequest);

    /**
     * 
     * @param contractid
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSignCreate", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.GetSignCreate")
    @ResponseWrapper(localName = "getSignCreateResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.GetSignCreateResponse")
    public String getSignCreate(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "contractid", targetNamespace = "")
        String contractid);

    /**
     * 
     * @param submitRequest
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitContractWithEseal", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.SubmitContractWithEseal")
    @ResponseWrapper(localName = "submitContractWithEsealResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.SubmitContractWithEsealResponse")
    public String submitContractWithEseal(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "submitRequest", targetNamespace = "")
        SubmitRequest submitRequest);

    /**
     * 
     * @param token
     * @param contractRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addContract", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.AddContract")
    @ResponseWrapper(localName = "addContractResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.AddContractResponse")
    public String addContract(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "contractRequest", targetNamespace = "")
        ContractRequest contractRequest);

    /**
     * 
     * @param contractid
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMsgCode", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.GetMsgCode")
    @ResponseWrapper(localName = "getMsgCodeResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.GetMsgCodeResponse")
    public String getMsgCode(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "contractid", targetNamespace = "")
        String contractid);

    /**
     * 
     * @param cancelRequest
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelContractV2", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.CancelContractV2")
    @ResponseWrapper(localName = "cancelContractV2Response", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.CancelContractV2Response")
    public String cancelContractV2(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "cancelRequest", targetNamespace = "")
        CancelRequest cancelRequest);

    /**
     * 
     * @param submitContractRequest
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitContract", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.SubmitContract")
    @ResponseWrapper(localName = "submitContractResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.SubmitContractResponse")
    public String submitContract(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "submitContractRequest", targetNamespace = "")
        SubmitContractRequest submitContractRequest);

    /**
     * 
     * @param amount
     * @param subject
     * @param contractid
     * @param notifyUrl
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createContractPayQr", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.CreateContractPayQr")
    @ResponseWrapper(localName = "createContractPayQrResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.CreateContractPayQrResponse")
    public String createContractPayQr(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "contractid", targetNamespace = "")
        String contractid,
        @WebParam(name = "subject", targetNamespace = "")
        String subject,
        @WebParam(name = "amount", targetNamespace = "")
        Double amount,
        @WebParam(name = "notifyUrl", targetNamespace = "")
        String notifyUrl);

    /**
     * 
     * @param contractno
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getContractUuid", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.GetContractUuid")
    @ResponseWrapper(localName = "getContractUuidResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.GetContractUuidResponse")
    public String getContractUuid(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "contractno", targetNamespace = "")
        String contractno);

    /**
     * 
     * @param submitRequest
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitCARetry", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.SubmitCARetry")
    @ResponseWrapper(localName = "submitCARetryResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.SubmitCARetryResponse")
    public String submitCARetry(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "submitRequest", targetNamespace = "")
        SubmitRequest submitRequest);

    /**
     * 
     * @param submitRequest
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "submitContractWithSign", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.SubmitContractWithSign")
    @ResponseWrapper(localName = "submitContractWithSignResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.SubmitContractWithSignResponse")
    public String submitContractWithSign(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "submitRequest", targetNamespace = "")
        SubmitRequest submitRequest);

    /**
     * 
     * @param guestmobile
     * @param contractid
     * @param guestname
     * @param token
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resendMsg", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.ResendMsg")
    @ResponseWrapper(localName = "resendMsgResponse", targetNamespace = "http://server.ws.api.contract.goldpalm.com/", className = "com.maitao.weservice.ResendMsgResponse")
    public String resendMsg(
        @WebParam(name = "token", targetNamespace = "")
        String token,
        @WebParam(name = "contractid", targetNamespace = "")
        String contractid,
        @WebParam(name = "guestname", targetNamespace = "")
        String guestname,
        @WebParam(name = "guestmobile", targetNamespace = "")
        String guestmobile);

}
